### PR TITLE
Zab/heartbeat fencing tweaks

### PR DESCRIPTION
**Pull request by zabbo**

### CODE REVIEW

**Comment by versity-github** [comment]
Build 7 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/7/ git: 7b65767803b4b9059ff75afc9d089352be241dc0

**Review by aversecat — APPROVED** [review]

**Comment by versity-github** [comment]
Build 8 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/8/ git: 5eee65ab45149260e4a851a20fa68a3b5723abb6

**Comment by versity-github** [comment]
Build 9 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/9/ git: a6a5bd26fce6e65491bd836c42e1a8594be13ca8

**Comment by versity-github** [comment]
Build 10 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/10/ git: 904c5dce90f0d9a64150d9fcd400221d39cbaf82

**Pull request merged**
