### PR TITLE
Parallel restore fixes, features, test script. **WIP**

### PR DESCRIPTION
**Pull request by aversecat**
Work items:

- [ ] - quota support
- [ ] - project ID
- [ ] - retention
- [x] - validation code in the form of a usable restore thing (restore_copy)
- [ ] - rebase to `main`
- [ ] - mounted checks
- [ ] - meta_dev bits test check
- [ ] - Make the library more usable by implementing requested changes from scoutam team

### CODE REVIEW

**Comment by versity-github** [comment]
Build 154 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/154/ git: a4784f422e66cb8189ee399639b9e4816e6d78bb

**Comment by versity-github** [comment]
Build 128 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/128/ git: a4784f422e66cb8189ee399639b9e4816e6d78bb

**Comment by versity-github** [comment]
Build 155 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/155/ git: 8cd5414cf67d4fd1ba7e4232d0728346d69b329d

**Comment by versity-github** [comment]
Build 129 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/129/ git: 8cd5414cf67d4fd1ba7e4232d0728346d69b329d

**Comment by versity-github** [comment]
Build 156 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/156/ git: 5401e2250ea49abe7a889a7f49009cc0aa0b7cc6

**Comment by versity-github** [comment]
Build 130 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/130/ git: 5401e2250ea49abe7a889a7f49009cc0aa0b7cc6

**Comment by versity-github** [comment]
Build 157 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/157/ git: 40b3f6a87f1392ec1c1f0cf903ed77b667a6b93e

**Comment by versity-github** [comment]
Build 158 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/158/ git: 07a4132aba19f0f0ce9c88184758bdbf609947db

**Comment by versity-github** [comment]
Build 131 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/131/ git: 40b3f6a87f1392ec1c1f0cf903ed77b667a6b93e

**Comment by versity-github** [comment]
Build 160 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/160/ git: a451db7310aa71ddfdfc571aa2f82c16a09adae4

**Comment by versity-github** [comment]
Build 132 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/132/ git: 07a4132aba19f0f0ce9c88184758bdbf609947db

**Comment by versity-github** [comment]
Build 133 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/133/ git: d79be4eaeb953470b2b200d45be13891bf572192

**Comment by versity-github** [comment]
Build 134 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/134/ git: a451db7310aa71ddfdfc571aa2f82c16a09adae4

**Comment by versity-github** [comment]
Build 161 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/161/ git: 03e69c6f4fd5b616ea1df154cf2c9e531c1f3bb2

**Comment by versity-github** [comment]
Build 135 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/135/ git: 03e69c6f4fd5b616ea1df154cf2c9e531c1f3bb2

**Comment by versity-github** [comment]
Build 162 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/162/ git: f7faff33a0cf42f052ab669b35ca483c49fb5907

**Comment by versity-github** [comment]
Build 136 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/136/ git: f7faff33a0cf42f052ab669b35ca483c49fb5907

**Comment by aversecat** [comment]
@zabbo Updated this branch with all my changes: 2x fixes as discussed, plus the addition of test scripts and `restore_copy` tool I wrote for validation purposes. Still requires some test harnass code to actually use it to validate all the metadata, but it should be pretty close to feature complete.

**Comment by versity-github** [comment]
Build 167 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/167/ git: 8e8db0a2e892ea446b211fda0c1a9e03778887ac

**Comment by versity-github** [comment]
Build 142 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/142/ git: 8e8db0a2e892ea446b211fda0c1a9e03778887ac

**Comment by versity-github** [comment]
Build 172 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/172/ git: 10b2fabba74192300f1202a0587bd7eda62a4251

**Comment by versity-github** [comment]
Build 146 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/146/ git: 10b2fabba74192300f1202a0587bd7eda62a4251

**Comment by aversecat** [comment]
Rebased and includes @h-shaffer changes. Note base branch also needs rebasing to 1.20 at this point.

**Comment by versity-github** [comment]
Build 173 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/173/ git: 0d43feac35660050d484ebecc2fbcad086de82d2

**Comment by versity-github** [comment]
Build 147 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/147/ git: 9448fcbc17c8f280be113b6b98ec4001ce630cd0

**Comment by versity-github** [comment]
Build 148 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/148/ git: 0d43feac35660050d484ebecc2fbcad086de82d2

**Comment by versity-github** [comment]
Build 184 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/184/ git: 442963b0f9e2a8999be90d8be1ef3e444e5662db

**Comment by versity-github** [comment]
Build 159 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/159/ git: 442963b0f9e2a8999be90d8be1ef3e444e5662db

**Comment by versity-github** [comment]
Build 194 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/194/ git: 89a0d692e45b35d808b993052b082a6371757617

**Comment by versity-github** [comment]
Build 170 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/170/ git: 89a0d692e45b35d808b993052b082a6371757617

**Comment by versity-github** [comment]
Build 199 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/199/ git: 34a7b2cdf1906e9a8b81d16dd551a4cfa9a6b43e

**Comment by versity-github** [comment]
Build 175 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/175/ git: 34a7b2cdf1906e9a8b81d16dd551a4cfa9a6b43e

**Pull request closed without merging**
