### PR TITLE
dm lineair support.

### PR DESCRIPTION
**Pull request by aversecat**
Branch contains some testing stuff:
- test iterator - repeats tests N times between mounts
- dm-lineair - avoids using loopback devices to dupe access to block devices, uses dm lineair instead

### CODE REVIEW

**Comment by versity-github** [comment]
Build 71 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/71/ git: 07ec09e83955c776892260bf739244a367869607

**Comment by versity-github** [comment]
Build 97 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/97/ git: 07ec09e83955c776892260bf739244a367869607

**Comment by aversecat** [comment]
Dropped the iterator patch from this. This just contains the dm lineair patch now.

**Comment by versity-github** [comment]
Build 82 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/82/ git: 8e81b8974744281f6cd83c5acc3f3609554b51b7

**Pull request closed without merging**
