### PR TITLE
Zab/dmsetup test devices

### PR DESCRIPTION
**Pull request by zabbo**

### CODE REVIEW

**Comment by versity-github** [comment]
Build 83 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/83/ git: 03ab5cedb6ef3662dcbc2be8f578c449c25e950c

**Comment by versity-github** [comment]
Build 108 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/108/ git: 03ab5cedb6ef3662dcbc2be8f578c449c25e950c

**Review by aversecat — APPROVED** [review]

**Comment by aversecat** [comment]
Though:

```
[1173856.213362] scoutfs f.f1f3a4.r.e25354 error: super block has invalid crc 0x0a5bed57, calculated 0x842a208c
lock-recover-invalidate unexpected messages in dmesg
```

**Comment by zabbo** [comment]
> (this is on el8)

Bummer, was that from running locally?

**Comment by aversecat** [comment]
> Bummer, was that from running locally?

Yes, this is my rocky 8 VM

**Comment by zabbo** [comment]
It seems to run fine in the jenkins env and in my VMs, so let's merge this and see if the crc failures were an artifact of the cache configuration of Aeuke's el8 VM.

**Pull request merged**
