### PR TITLE
scoutfs mmap support

### PR DESCRIPTION
**Pull request by agrover**
[copied from now-defunct scoutfs-kmod-dev repo](https://github.com/versity/scoutfs-kmod-dev/pull/34) so it doesn't get lost.

> Please review this patch set which adds support for both read and writable mmap support for scouts.

Needs rebasing and updating.

### CODE REVIEW

**Comment by versity-github** [comment]
Build 51 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/51/ git: e064c439ffbf58e1b408f38152492833dc5e02cd

**Comment by versity-github** [comment]
Build 7 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/7/ git: e064c439ffbf58e1b408f38152492833dc5e02cd

**Comment by versity-github** [comment]
Can one of the admins verify this patch?

**Comment by aversecat** [comment]
Obsoleted by #175

**Pull request closed without merging**
