### PR TITLE
Zab/log merging speedups

### PR DESCRIPTION
**Pull request by zabbo**

### CODE REVIEW

**Review by aversecat — APPROVED** [review]

**Comment by versity-github** [comment]
Build 91 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/91/ git: e9ad61b444e732fe1b93edc762d59f1edeb024fe

**Comment by versity-github** [comment]
Build 117 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/117/ git: e9ad61b444e732fe1b93edc762d59f1edeb024fe

**Comment by gcymbalski** [comment]
retest

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 92 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/92/ git: e9ad61b444e732fe1b93edc762d59f1edeb024fe

**Comment by versity-github** [comment]
Build 118 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/118/ git: e9ad61b444e732fe1b93edc762d59f1edeb024fe

**Comment by versity-github** [comment]
Build 93 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/93/ git: e9ad61b444e732fe1b93edc762d59f1edeb024fe

**Pull request merged**
