### PR TITLE
Auke/el8 pr test

### PR DESCRIPTION
**Pull request by aversecat**
do not merge, just a quick test.

### CODE REVIEW

**Comment by versity-github** [comment]
Build 52 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/52/ git: 03541e039b6655369c493561dbef6311967014b4

**Comment by versity-github** [comment]
Build 24 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/24/ git: 03541e039b6655369c493561dbef6311967014b4

**Comment by gcymbalski** [comment]
retest

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 25 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/25/ git: 03541e039b6655369c493561dbef6311967014b4

**Comment by versity-github** [comment]
Build 26 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/26/ git: 03541e039b6655369c493561dbef6311967014b4

**Comment by versity-github** [comment]
Build 53 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/53/ git: 03541e039b6655369c493561dbef6311967014b4

**Comment by versity-github** [comment]
Build 55 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/55/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by versity-github** [comment]
Build 28 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/28/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by aversecat** [comment]
retest

**Comment by versity-github** [comment]
Build 30 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/30/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by versity-github** [comment]
Build 57 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/57/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by aversecat** [comment]
retest

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 35 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/35/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by versity-github** [comment]
Build 62 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/62/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by versity-github** [comment]
Build 63 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/63/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by versity-github** [comment]
Build 36 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/36/ git: 7e09fb0755edda251d16288d218d4674c1c5d5c4

**Comment by versity-github** [comment]
Build 37 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/37/ git: 142c7dce9c220627d96b491bac9e359f1fd009c5

**Comment by versity-github** [comment]
Build 64 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/64/ git: 142c7dce9c220627d96b491bac9e359f1fd009c5

**Comment by versity-github** [comment]
Build 65 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/65/ git: e8971b802019bbbce209cfdb82a357b184ab0160

**Comment by versity-github** [comment]
Build 38 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/38/ git: e8971b802019bbbce209cfdb82a357b184ab0160

**Comment by versity-github** [comment]
Build 39 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/39/ git: c1e2b1ca67d93a0039077bd8978d12f56f9788ff

**Comment by versity-github** [comment]
Build 66 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/66/ git: c1e2b1ca67d93a0039077bd8978d12f56f9788ff

**Pull request closed without merging**
