### PR TITLE
scoutfs: introduce CodingStyle.txt

### PR DESCRIPTION
**Pull request by agrover**
Add a coding style document that tries to record the conventions that
the project uses.  It seemed more appropriate to put it up in the -kmod
git repo context rather than in src/ which would end up in fs/scoutfs/
upstream.

Signed-off-by: Zach Brown <zab@versity.com>

### CODE REVIEW

**Comment by agrover** [comment]
[copying PR from PR against old repo](https://github.com/versity/scoutfs-kmod-dev/pull/39) I think the only question is exactly where to put it. Why not toplevel?

**Comment by versity-github** [comment]
Build 52 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/52/ git: 8ee41caa24f89e748e17836103eb7ea356b523a4

**Comment by zabbo** [comment]
> [copying PR from PR against old repo](https://github.com/versity/scoutfs-kmod-dev/pull/39) I think the only question is exactly where to put it. Why not toplevel?

Well, I'd first ask if we want it to begin with.  It landed with a resounding thud when I first threw it together.  Is it needed?

**Comment by agrover** [comment]
Yeah I think it's a good idea. To just have a place to put style preferences. We may come up with more.

 I think I just read the PR and got the info that way but that's kinda cheating or something.

**Comment by versity-github** [comment]
Build 6 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/6/ git: 8ee41caa24f89e748e17836103eb7ea356b523a4

**Comment by versity-github** [comment]
Can one of the admins verify this patch?

**Comment by versity-github** [comment]
This won't automatically run in continuous integration without approval. A member of the Versity organization must allow it.

**Comment by zabbo** [comment]
This is ancient and I don't think we'll be doing this.

**Pull request closed without merging**
