### PR TITLE
test for jenkins

### PR DESCRIPTION
**Pull request by benmcclelland**

### CODE REVIEW

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
restest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by benmcclelland** [comment]
retest

**Comment by zabbo** [comment]
Test "success" isn't a negative lack of failure, it's a positive result of running the expected tests.  If we skipped tests we don't know if we broke them and the tests didn't succeed.

**Pull request closed without merging**
