### PR TITLE
Zab/data prealloc options

### PR DESCRIPTION
**Pull request by zabbo**

### CODE REVIEW

**Comment by versity-github** [comment]
Build 243 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/243/ git: 51c01132dab4280a91b12d3eb5b6655cb9fb3189

**Comment by versity-github** [comment]
Build 244 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/244/ git: df03863f983199635849d3d8b7b3bdb547ca0ca7

**Comment by versity-github** [comment]
Build 245 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/245/ git: d5ddf1ecaca8e48b94e2703d2f02464db729baa6

**Comment by zabbo** [comment]
This failure was the known issue of the orphan scanner lock attempts triggering the blocked task warning while very large deletions are in flight.

**Pull request merged**
