### PR TITLE
Encode git info into spec to keep git info in final kmod

### PR DESCRIPTION
**Pull request by gcymbalski**

### CODE REVIEW

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 123 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/123/ git: e43dea8846cfd5311623e3e782895659f6e3d07b

**Comment by versity-github** [comment]
Build 99 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/99/ git: e43dea8846cfd5311623e3e782895659f6e3d07b

**Comment by versity-github** [comment]
Build 100 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/100/ git: e43dea8846cfd5311623e3e782895659f6e3d07b

**Comment by versity-github** [comment]
Build 126 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/126/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by versity-github** [comment]
Build 101 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/101/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 104 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/104/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by versity-github** [comment]
Build 129 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/129/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 106 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/106/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by versity-github** [comment]
Build 131 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/131/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 107 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/107/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Comment by versity-github** [comment]
Build 132 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/132/ git: a4bc3fb27d03112531272ac9d436825d7507fd56

**Review by aversecat — APPROVED** [review]

**Pull request merged**
