### PR TITLE
Use seqlock instead of seqcount in server

### PR DESCRIPTION
**Pull request by zabbo**
The server had a few lower level seqcounts that it used to protect state.  One user got it wrong by forgetting to disable pre-emption around writers.  Debug kernels warned as write_seqcount_begin() was called without preemption disabled.

We fix that user and make it easier to get right in the future by having one higher level seqlock and using that consistently for seq read begin/retry and write lock/unlock patterns.

### CODE REVIEW

**Comment by versity-github** [comment]
Build 61 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/61/ git: 006f429f722d4fb830f75c2dcb4cd27fc2f92409

**Comment by versity-github** [comment]
Build 88 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/88/ git: 006f429f722d4fb830f75c2dcb4cd27fc2f92409

**Review by aversecat — APPROVED** [review]
lgtm

**Comment by versity-github** [comment]
Build 94 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/94/ git: 006f429f722d4fb830f75c2dcb4cd27fc2f92409

**Comment by versity-github** [comment]
Build 67 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/67/ git: 006f429f722d4fb830f75c2dcb4cd27fc2f92409

**Comment by versity-github** [comment]
Build 69 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/69/ git: 006f429f722d4fb830f75c2dcb4cd27fc2f92409

**Comment by versity-github** [comment]
Build 95 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/95/ git: 006f429f722d4fb830f75c2dcb4cd27fc2f92409

**Pull request merged**
