### PR TITLE
POSIX ACL fixes for el8, plus tests

### PR DESCRIPTION
**Pull request by aversecat**
- test cases for basic acl access patterns (directory, symlink, inheritance of default acls, user/group bits)
- fix ACLs on el8

### CODE REVIEW

**Comment by versity-github** [comment]
Build 195 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/195/ git: 341b1ae768a5cbbc782570cf3601a6bc54204ec2

**Comment by versity-github** [comment]
Build 171 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/171/ git: 985416d5647941971c3f01ebab814a6c15436f31

**Comment by versity-github** [comment]
Build 196 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/196/ git: 985416d5647941971c3f01ebab814a6c15436f31

**Comment by versity-github** [comment]
Build 172 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/172/ git: 985416d5647941971c3f01ebab814a6c15436f31

**Comment by versity-github** [comment]
Build 197 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/197/ git: 7b039a1d18c0ca62ae1046b8d0c757cec0eba2b7

**Comment by versity-github** [comment]
Build 173 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/173/ git: 7b039a1d18c0ca62ae1046b8d0c757cec0eba2b7

**Comment by aversecat** [comment]
retest

**Comment by versity-github** [comment]
Build 174 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/174/ git: 7b039a1d18c0ca62ae1046b8d0c757cec0eba2b7

**Comment by versity-github** [comment]
Build 198 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/198/ git: 7b039a1d18c0ca62ae1046b8d0c757cec0eba2b7

**Review by zabbo — APPROVED** [review]

**Comment by zabbo** [comment]
The el8 failure was unrelated to these changes.. it has to do with trying to fence a client that doesn't reconnect but which never had a rid assigned.

**Pull request merged**
