### PR TITLE
Ignore spurious KASAN unwind warning

### PR DESCRIPTION
**Pull request by zabbo**
KASAN could raise a spurious warning if the unwinder started in code without ORC metadata and tried to access in the KASAN stack frame redzones.  This was fixed upstream but we can rarely see it in older kernels.  We can ignore these messages.

### CODE REVIEW

**Comment by versity-github** [comment]
Build 84 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/84/ git: b552406427ba636b5d12b184ca184ac3e086542a

**Review by aversecat — APPROVED** [review]

**Comment by versity-github** [comment]
Build 109 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/109/ git: b552406427ba636b5d12b184ca184ac3e086542a

**Comment by versity-github** [comment]
Build 110 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/110/ git: b552406427ba636b5d12b184ca184ac3e086542a

**Comment by gcymbalski** [comment]
test this please

**Comment by gcymbalski** [comment]
retest

**Comment by versity-github** [comment]
Build 85 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/85/ git: b552406427ba636b5d12b184ca184ac3e086542a

**Comment by versity-github** [comment]
Build 111 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/111/ git: b552406427ba636b5d12b184ca184ac3e086542a

**Pull request merged**
