### PR TITLE
Implement support for returning -ENOSPC before filesystem runs out of space

### PR DESCRIPTION
**Pull request by agrover**
Prelim, WIP, etc.

### CODE REVIEW

**Comment by versity-github** [comment]
Build 70 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/70/ git: f7229d8ef5abc21bd82583bedf7c531f00c4a2bb

**Comment by versity-github** [comment]
Build 71 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/71/ git: f7229d8ef5abc21bd82583bedf7c531f00c4a2bb

**Comment by versity-github** [comment]
Build 76 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/76/ git: b5c99d6952e9b230661f14a046ec242016e1377c

**Comment by versity-github** [comment]
Build 77 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/77/ git: 7f67a0ce468a250803535ccac57df8e425bbcd90

**Comment by agrover** [comment]
Status: Test currently passes for me locally. Using new createmany "-s" parameter to allocate data for each file causes  second phase of createmany to fail, and I don't understand why this changes things.

**Comment by versity-github** [comment]
Build 80 http://jenkins-prod.vpn.versity.com:8080/job/scoutfs-run-pr/80/ git: 8674ce6adebd4c7fd89ddca1c79403ae01aee23a

**Comment by zabbo** [comment]
> Status: Test currently passes for me locally. Using new createmany "-s" parameter to allocate data for each file causes second phase of createmany to fail, and I don't understand why this changes things.

Just to leave a record of our slack chat: I think what could be happening here is due to deleted items staying in the log btrees.  For deletion to reclaim space it has to delete values when leaving behind deletion keys.  That makes the ration of the key size to value lengths of the item population determine if deletion is going to reclaim space or not.  When you add extents, you add items that only have keys and no values.. they could be pushing the total key bytes beyond the total value lengths of the item population that deletion can reclaim space from.

**Comment by zabbo** [comment]
ENOSPC has been merged, we no longer need this WIP branch.

**Pull request closed without merging**
