### PR TITLE
Add `bc` to test requirement.

### PR DESCRIPTION
**Pull request by aversecat**

### CODE REVIEW

**Comment by versity-github** [comment]
Build 21 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/21/ git: 07f0ef33e24449a1a2294228fc947a44df2bb948

**Comment by versity-github** [comment]
Build 48 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/48/ git: 07f0ef33e24449a1a2294228fc947a44df2bb948

**Comment by aversecat** [comment]
retest

**Comment by versity-github** [comment]
Build 34 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/34/ git: 07f0ef33e24449a1a2294228fc947a44df2bb948

**Comment by versity-github** [comment]
Build 61 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/61/ git: 07f0ef33e24449a1a2294228fc947a44df2bb948

**Comment by versity-github** [comment]
Build 48 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr-el8/48/ git: d4d2b0850b46e4ec5a3d7bce63e077dc2c1a0f95

**Comment by versity-github** [comment]
Build 76 http://jenkins.vpn.versity.com:8080/job/scoutfs-run-pr/76/ git: d4d2b0850b46e4ec5a3d7bce63e077dc2c1a0f95

**Pull request merged**
